name: EjectDrives
options:
  bundleIdPrefix: com.yongza
  deploymentTarget:
    macOS: "13.0"
  developmentLanguage: en

settings:
  base:
    SWIFT_VERSION: "5.0"
    MACOSX_DEPLOYMENT_TARGET: "13.0"
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: 495S4FVMCB
    ENABLE_HARDENED_RUNTIME: YES
    PRODUCT_BUNDLE_IDENTIFIER: com.yongza.ejectdrives
    MARKETING_VERSION: "0.4.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  EjectDrives:
    type: application
    platform: macOS
    sources:
      - path: AppDelegate.swift
      - path: main.swift
      - path: DiskArbitrationBackend.swift
    entitlements:
      path: EjectDrives.entitlements
    info:
      path: Info.plist
      properties:
        CFBundleName: EjectDrives
        CFBundleDisplayName: EjectDrives
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        LSMinimumSystemVersion: "13.0"
        LSUIElement: true
        NSPrincipalClass: NSApplication
        LSApplicationCategoryType: public.app-category.utilities
        NSHumanReadableCopyright: "EjectDrives by yongZa"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yongza.ejectdrives
        DEVELOPMENT_TEAM: 495S4FVMCB
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_STYLE: Automatic
        ENABLE_HARDENED_RUNTIME: YES
        ENABLE_APP_SANDBOX: YES
